HFSclient/Models/League.cs
using System.Collections.Generic;

namespace HFSclient.Models
{
  public class League 
  {
    public League() 
    {
      this.Groups = new HashSet<Group>();
    }
    public int LeagueId { get; set; }
    public string LeagueName { get; set; }
    public int CurrentSeason { get; set; }
    public int CurrentWeek { get; set; }
    public virtual ICollection<Group> Groups { get; }  
  }
}

HFSclient/Controllers/RostersController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using HFSclient.Models;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;

namespace HFSclient.Controllers 
{ 
  public class RostersController : Controller
  {
    public readonly HFSclientContext _db;
    public RostersController(HFSclientContext db)
    {
      _db = db;
    }
    public ActionResult Index(int id)
    {
      List<Roster> model = _db.Rosters.Where(x => x.GroupId == id).ToList();
      ViewBag.Group = _db.Groups.FirstOrDefault(x => x.GroupId == id);
      return View(model);
    }
    public ActionResult Search(int id)
    {
      ViewBag.GroupId = id;
      return View();
    }
    [HttpPost]
    public async Task<ActionResult> Search(int id, string LastName)// Search for Players
    {
      ViewBag.GroupId = id;
      var model = await Player.SearchPlayer(LastName);
      return View("PlayerSearch", model);      
    }
    public ActionResult AddPlayer(int id, int groupId) //commish add players to rosterc
    {
      System.Console.WriteLine(_db.Rosters.Where(x => x.GroupId == groupId).Count());
      if(_db.Rosters.Where(x => x.GroupId == groupId).Count() <= 12)   //    Sets roster size
      {
        System.Console.WriteLine(id);
        System.Console.WriteLine(groupId);
        var p = Player.GetPlayerFromApi(id); 
        Roster roster = new Roster();
        roster.GroupId = groupId;
        roster.PlayerId = id;
        roster.Position = "bench";
        roster.FootballPosition = p.Result.Position;
        roster.LastName = p.Result.LastName;
        roster.FirstName = p.Result.FirstName;
        _db.Rosters.Add(roster);
        _db.SaveChanges();
      }
      else
      {
        //send error back "over roster size limit"
      }
      return RedirectToAction("Index", new { id = groupId}); //might have to change which view
    }  
    public ActionResult Details(int id)
    {
      int PlayerId = id;

      var model = Game.GetGameById(PlayerId).Result;
      Player p = Player.GetPlayerFromApi(model.PlayerId).Result;
      ViewBag.FirstName = p.FirstName;
      ViewBag.LastName = p.LastName;
      ViewBag.Position = p.Position;
      return View(model);
    }

    // public Task<ActionResult> Edit(int id )
    // {
    //   Roster r = _db.Rosters.Where(x => x.RosterId).FirstOrDefault();
    //   View(r);
    // }
    
    // [HttpPost]//may need to be a put
    // [Authorize(Roles = "Administrator")]
    public ActionResult Edit(int id)
    {
      var roster = _db.Rosters.FirstOrDefault(x => x.RosterId == id);
      if(roster.Position == "bench")
      {
        roster.Position = roster.FootballPosition; 
      }
      else
      {
        roster.Position = "bench";
      }
      
      _db.Entry(roster).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index", new { id = roster.GroupId});
    }
    public ActionResult RemovePlayer(int id)
    {
      var model = _db.Rosters.FirstOrDefault(x => x.RosterId == id);
      return View(model);
    }
    public ActionResult ConfirmRemove(int id, int groupId)
    {
      var player = _db.Rosters.FirstOrDefault(x => x.PlayerId == id && x.GroupId == groupId);
      _db.Rosters.Remove(player);
      _db.SaveChanges();
      return RedirectToAction("Index", new {});
    }   
  }
}

HFSclient/Controllers/SchedulesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using HFSclient.Models;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using System.Net.Http;
using System;
using System.Threading.Tasks;
using HFSclient.Wrappers;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HFSclient.Controllers
{
  public class SchedulesController : Controller
  {
    public readonly HFSclientContext _db;
    public SchedulesController(HFSclientContext db)
    {
      _db = db; 
    }
    public  ActionResult  Index(int id)
    {
        
      List<Schedule> model = _db.Schedules.ToList();
      return View(model);
    }

    [Authorize(Roles = "Administrator")]
    public ActionResult Create()
    {
      return View();
    }
  
    [Authorize(Roles = "Administrator")]
    [HttpPost]
    public ActionResult Create(int GroupId1, int GroupId2, int Week, int Team1Score, int Team2Score )
    {
      Schedule schedule = new Schedule();
      if(GroupId1 != 0)
      {
        schedule.GroupId1 = GroupId1;
      }
      if(GroupId2 != 0)
      {
        schedule.GroupId2 = GroupId2;
      }
      if(Week != 0) 
      { 
        schedule.Week = Week; 
      }  
      if(Team1Score != 0)
      {
        schedule.Team1Score = Team1Score;
      }
      if(Team2Score != 0)
      {  
        schedule.Team2Score = Team2Score; 
      }

      _db.Schedules.Add(schedule);
      _db.SaveChanges();
      return RedirectToAction("Index");  
    }
    public ActionResult Details(int id)
    {
      var thisSchedule = _db.Schedules 
        .FirstOrDefault(x => x.ScheduleId == id);
      ViewBag.Team1Trackers = _db.Trackers.Where(x => x.ScheduleId == id && x.GroupId == thisSchedule.GroupId1).OrderBy(x => x.Position); 
      ViewBag.Team2Trackers = _db.Trackers.Where(x => x.ScheduleId == id && x.GroupId == thisSchedule.GroupId2).OrderBy(x => x.Position); 
      ViewBag.Team1Name = _db.Groups.Where(c => c.GroupId ==  thisSchedule.GroupId1).FirstOrDefault().TeamName;
      ViewBag.Team2Name = _db.Groups.Where(c => c.GroupId ==  thisSchedule.GroupId2).FirstOrDefault().TeamName;
      return View(thisSchedule);
    }

    [Authorize(Roles = "Administrator")] 
    public ActionResult Edit(int id)
    {
      var thisSchedule = _db.Schedules
        .FirstOrDefault(x => x.ScheduleId == id);
      return View(thisSchedule);
    }
    
    [Authorize(Roles = "Administrator")]
    [HttpPost]
    public ActionResult Edit(Schedule schedule)
    {
      _db.Entry(schedule).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = schedule.ScheduleId});
    }
//   public async Task<ActionResult> Sim(int id, int week )
//   {
          
// System.Console.WriteLine(week);
//     var teams = _db.Groups.Where(x => x.LeagueId  == id).ToList();
//       List<Schedule> games = new List<Schedule>();
//       foreach (Group team in teams) 
//       {
//         List<Schedule> s = _db.Schedules.Where(x => x.GroupId1 == team.GroupId).ToList();
//         foreach (Schedule  schedule in s)
//         {
//           if(schedule.Week == week)
//           {
            
//             if(!(schedule.IsComplete))
//             {
//               games.Add(schedule);
//               System.Console.WriteLine("here");
//             }
//           }
            
//         }
          
//       }
//       return RedirectToAction("Runsim", new {id = id, schedules = games});
//   }
    
    
    public async Task<ActionResult> RunSim(int id , int week  ) //might be schedule id 
    {
      var teams = _db.Groups.Where(x => x.LeagueId  == id).ToList();
      List<Schedule> games = new List<Schedule>();
      foreach (Group team in teams) 
      {
        List<Schedule> s = _db.Schedules.Where(x => x.GroupId1 == team.GroupId).ToList();
        
        foreach (Schedule  schedule in s)
        {
          //System.Console.WriteLine(schedule.Team1Name);
          if(schedule.Week == week)
          {
            System.Console.WriteLine(schedule.Team1Name);
            
              games.Add(schedule);
              System.Console.WriteLine(games.Count());
              System.Console.WriteLine("here");
            
          }
            
        }
          
      }



      System.Console.WriteLine(games.Count());
      foreach (Schedule schedule in games)
      {
      
      List<Roster> roster1 = _db.Rosters.Where(x => x.GroupId == schedule.GroupId1).ToList();
      List<Roster> roster2 = _db.Rosters.Where(x => x.GroupId == schedule.GroupId2).ToList();
      int teamscore = 0;
      foreach (Roster roster in roster1)
      {
          Game game = await Game.GetGameByWeek(schedule.Week, roster.PlayerId); //get game by roster.GameId;
          System.Console.WriteLine(game.Team);
          Tracker tracker = new Tracker {
            GameId = game.GameId,
            GroupId = schedule.GroupId1,
            Position = roster.Position,
            FirstName = roster.FirstName,
            LastName = roster.LastName,
            Points = game.CalcScore()
          }; //calculate fantasy points here 
          if(tracker.Position != "bench")//make sure not a bench player and add to schedule points for the team
          {
            teamscore += tracker.Points;
          }
          tracker.ScheduleId = schedule.ScheduleId;
          _db.Trackers.Add(tracker);
      }
      schedule.Team1Score = teamscore;
      teamscore = 0;
      foreach (Roster roster in roster2)
      {
          Game game = await Game.GetGameByWeek(schedule.Week, roster.PlayerId); //get game by roster.GameId;
          Tracker tracker = new Tracker {
            GameId = game.GameId,
            GroupId = schedule.GroupId2,
            Position = roster.Position,
            FirstName = roster.FirstName,
            LastName = roster.LastName,
            Points = game.CalcScore()
          }; //calculate fantasy points here 
          if(tracker.Position != "bench")//make sure not a bench player and add to schedule points for the team
          {
            teamscore += tracker.Points;
          }
          tracker.ScheduleId = schedule.ScheduleId;
          _db.Trackers.Add(tracker);
          
      }
      schedule.Team2Score = teamscore;
      schedule.IsComplete = true;
      //update standings

      Standing standingTeam1 = _db.Standings.Where(x => x.GroupId == schedule.GroupId1).FirstOrDefault();
      Standing standingTeam2 = _db.Standings.Where(x => x.GroupId == schedule.GroupId2).FirstOrDefault();

      if(schedule.Team1Score > schedule.Team2Score)
      {
        standingTeam1.Wins++;
        standingTeam2.Losses++;
        standingTeam1.PtsFor += schedule.Team1Score;
        standingTeam2.PtsFor += schedule.Team2Score;
        standingTeam1.PtsAgst += schedule.Team2Score;
        standingTeam1.PtsAgst += schedule.Team1Score;
        
      }
      else if(schedule.Team1Score < schedule.Team2Score)
      {
        standingTeam2.Wins++;
        standingTeam1.Losses++;
        standingTeam2.PtsFor += schedule.Team2Score;
        standingTeam1.PtsFor += schedule.Team1Score;
        standingTeam2.PtsAgst += schedule.Team1Score;
        standingTeam1.PtsAgst += schedule.Team2Score;
        
      }
      else
      {
        standingTeam2.Ties++;
        standingTeam1.Ties++;
        standingTeam2.PtsFor += schedule.Team2Score;
        standingTeam1.PtsFor += schedule.Team1Score;
        standingTeam2.PtsAgst += schedule.Team1Score;
        standingTeam1.PtsAgst += schedule.Team2Score;
      }





      _db.Entry(standingTeam1).State = EntityState.Modified; 
      _db.Entry(standingTeam2).State = EntityState.Modified;
      _db.Entry(schedule).State = EntityState.Modified;;
      }
      League l = _db.Leagues.Where(x => x.LeagueId == id).FirstOrDefault();
      l.CurrentWeek++;
      _db.Entry(l).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Commish", "Leagues", new { id = id });
    }

    // 12345678  1   2   3  4  5 6   7  8
                                        // 1         12  13 14 15 16 17 18  12
                                        //2     12  24 25 26 27 28 23  12
                                        // 3    34  31 
    public ActionResult BuildSchedule(int id)                                         
    {
      List<Group> temp = _db.Groups.Where(x => x.LeagueId == id).ToList();
      System.Console.WriteLine(temp.Count()); 
      List<int> teams = new List<int>();
      foreach (Group group in temp)
      {
          teams.Add(group.GroupId);
      }
      //let teams = ["1",'2','3','4','5','6','7','8','9']
      int count = teams.Count();
      System.Console.WriteLine(count); 
      if( count % 2 == 1)
      {
        count++;
        teams.Add(0);
      }
      
      List<int> teams1 = teams.GetRange(0,count/2);
      // let teams1 = ["1",'2','3','4','5'];//5742
      // let teams2 = ['6','7','8','9',''];

      List<int> teams2 =teams.GetRange(count/2, count/2);

      
      // if(count % 2 == 1)
      // {
      // count++;
      // teams2.push('');
      // }
      for(int i = 0 ; i < 12; i++)
      {
          // console.log(teams1)
          // console.log(teams2)
          // console.log('')
        for(int j = 0; j < teams1.Count(); j++)
        {
          //console.log(teams1[j] + teams2[j]);//create game
          Schedule schedule =new Schedule();
          schedule.GroupId1 = teams1[j];
          schedule.GroupId2 = teams2[j];
          schedule.Team1Name = _db.Groups.Where(x => x.GroupId == schedule.GroupId1 ).FirstOrDefault().TeamName;
          schedule.Team2Name = _db.Groups.Where(x => x.GroupId == schedule.GroupId2 ).FirstOrDefault().TeamName;
          schedule.IsComplete = false;
          schedule.Week = i + 1;
          _db.Schedules.Add(schedule);
          
        }
        
        if(i % (count/2 - 1) == 0 && i != 0)
        {
           
          int tmp = teams1[teams1.Count() - 1];

HFSclient/Views/Leagues/Commish.cshtml
@{
  Layout = "_Layout";
}

@using HFSclient.Models


@Html.ActionLink(" Sim Week", "RunSim", "Schedules", new { id = @Model.LeagueId, week = @Model.CurrentWeek}, new { @class = "btn btn-info"})
@Html.ActionLink(" Generate Schedule", "BuildSchedule", "Schedules", new { id = @Model.LeagueId}, new { @class = "btn btn-info"})
@Html.ActionLink(" Back", "Details", null, new { id = @Model.LeagueId}, new { @class = "btn btn-info"})

HFSclient/Views/Leagues/Create.cshtml
@{
  Layout = "_Layout";
}

@model HFSclient.Models.League;

<h4>Add a new League</h4>

@using (Html.BeginForm())
{
  @Html.Label("League Name:")
  <br>
  @Html.TextBoxFor(model => model.LeagueName, new {@required="required"})
  <br><br>
  <input type="submit" value="Add New League" class="btn btn-success btn-sm" />
}
<br>
<p>@Html.ActionLink("Cancel", "Index", null, null, new {@class="btn btn-info btn-sm"})</p>







@* Create League
auto assign user as commissioner *@

HFSclient/Views/Leagues/Details.cshtml
@{
  Layout = "_Layout";
}

@using HFSclient.Models

<p>League details</p>
<hr />
<p><strong>Name:</strong> @ViewBag.League.LeagueName</p>
<hr />
<p>Owners in this League:</p>
<div class="box">
  <div class="inner-box">
    <table>
      @if (@Model.Count != 0)
      {
        @foreach (var league in Model)
        {
          <tr>
            <td>@league.TeamName</td>
            <td>@Html.ActionLink(" View Team", "Index", "Rosters", new { id = league.GroupId }, new { @class = "btn-btn-info"})</td>
            @if(@ViewBag.Owner != null)
            {
              <td>@Html.ActionLink(" Remove", "RemoveOwner", null, new { id = league.GroupId }, new { @class = "btn-btn-info"})</td>
              <td>@Html.ActionLink(" Add Player", "Search", "Rosters", new { id = league.GroupId }, new { @class = "btn-btn-info"})</td>
            }
          </tr>
        } 
      }
      else
      {
        <tr>
          <td>There are no Owners in this list.</td>
        </tr>
      }
    </table>
  </div>
</div> 
<br>
@if(@ViewBag.Owner != null)
{
  <p>@Html.ActionLink(" Edit League", "Edit", new { id = @ViewBag.League.LeagueId }, new {@class="btn btn-success btn-sm"})</p>
  <p>@Html.ActionLink(" Settings", "Commish", new { id = @ViewBag.League.LeagueId }, new {@class="btn btn-success btn-sm"})</p>
}
@Html.ActionLink(" See All Leagues", "Index", null, null, new {@class="btn btn-info btn-sm"})
@if(@Model.Count < 13)
{
  @Html.ActionLink(" Join League", "Join", new { id = @ViewBag.League.LeagueId }, new {@class="btn btn-success btn-sm"})
}
&nbsp;@Html.ActionLink(" View Schedule", "LeagueSchedule", "Schedules", new { id = @ViewBag.League.LeagueId }, new { @class="btn btn-info btn-sm"}) 

@Html.ActionLink(" View Standings", "Index", "Standings", new { id = @ViewBag.League.LeagueId }, new { @class="btn btn-info btn-sm"})
@* League
Current Players
User clicks on themselves -> Roster
History
Button View Standings *@

HFSclient/Views/Leagues/Edit.cshtml
@{
  Layout = "_Layout";
}
@model HFSclient.Models.League

<h3>Edit this League: @Html.DisplayFor(model => model.LeagueName)</h3>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.LeagueId)

  @Html.Label("League Name")
  @Html.EditorFor(model => model.LeagueName)

  <input type="submit" value="Save" class="btn btn-success btn-sm" />
}
<br>
<p>@Html.ActionLink("Cancel", "Details", null, new {id = Model.LeagueId }, new {@class="btn btn-info btn-sm"})</p>


@* Edit League
Remove Player
Change Name
Change Commissioner
Change Image *@

HFSclient/Views/Leagues/Index.cshtml
@{
  Layout = "_Layout";
}

@using HFSclient.Models;

@using (Html.BeginForm())
{
  <table>
    <tr>
      <td>Search for a League</td>
      <td>@Html.TextBox("Name")</td>
      <td><input type="submit" value="Search" class="btn btn-info btn-sm"/></td>
    </tr>
  </table>
}
<hr />
<p>Current Leagues</p>
<hr />
<div class="box">
  <div class="inner-box">
    <table>
      @if (@Model.Count == 0)
      {
        <tr>
          <td>There are no Leauges in this list.</td>
        </tr>
      }
      @foreach (League league in Model)
      {
        <tr>
          <td>@league.LeagueName</td>
          <td>@Html.ActionLink("View", "Details", new { id = league.LeagueId }, new {@class="btn btn-info btn-sm"} )</td>
        </tr>
      }
    </table>
  </div>
</div>
<br>
<p>@Html.ActionLink("Add New League", "Create", null, null, new {@class="btn btn-success btn-sm"})</p>
<p>@Html.ActionLink("See All Leagues", "Index", null, null, new {@class="btn btn-info btn-sm"})</p>

@* <p>@Html.ActionLink("Join a League", "Join", new { id = Model.LeagueId}, new {@class="btn btn-success btn-sm"})</p> *@





@* List of all Leagues
Button for Create
Button to join a league *@

HFSclient/Views/Leagues/Join.cshtml
@{
  Layout = "_Layout";
}

@using HFSclient.Models
@model HFSclient.Models.Group

<p>Join this League: @ViewBag.League.LeagueName</p>
<hr />
@using (Html.BeginForm())
{
  @* @Html.HiddenFor(model => model.LeagueId) *@
  @Html.Hidden("LeagueId", (int)@ViewBag.League.LeagueId)

  @Html.Label("Choose your teams name:")
  @Html.TextBoxFor(model => model.TeamName)

  <input type="submit" value="Join" class="btn btn-success btn-sm" />
}
<br>
<p>@Html.ActionLink("Cancel", "Index", null, null, new {@class="btn btn-info btn-sm"})</p>

HFSclient/Views/Leagues/RemoveOwner.cshtml
@{
  Layout = "_Layout";
}

@model HFSclient.Models.Group


<hr />
<p>Are you sure you want to remove this Owner?</p>
<hr />
@Html.Label("Team Name"): @Html.DisplayFor(model => model.TeamName)
@Html.ActionLink(" Remove", "RemoveOwner", null, new { id = Model.GroupId}, new { @class = "btn btn-info"})
<hr />