HFSclient/Models/Standing.cs
namespace HFSclient.Models
{
  public class Standing
  {
    public int LeagueId { get; set; }
    public int StandingId { get; set; }
    public int GroupId { get; set; }
    public string TeamName { get; set; } 
    public int Wins { get; set; }
    public int Ties { get; set; }
    public int Losses { get; set; }
    public int PtsFor { get; set; }
    public int PtsAgst { get; set; }
    public string LeagueName { get; set; }
  }
}

HFSclient/Controllers/LeaguesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using HFSclient.Models;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;


namespace HFSclient.Controllers
{
  public class LeaguesController : Controller
  {
    public readonly HFSclientContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public LeaguesController(UserManager<ApplicationUser> userManager, HFSclientContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    public ActionResult Index()
    {
      List<League> model = _db.Leagues.ToList();
      return View(model);
    }

    // [Authorize(Roles = "Administrator")]
    public ActionResult Create()
    {
      return View();
    }

    // [Authorize(Roles = "Administrator")]
    [HttpPost]
    public async Task<ActionResult> Create(League league)
    {
      league.CurrentWeek = 1;
      league.CurrentSeason = 1;
      _db.Leagues.Add(league);
      _db.SaveChanges();
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      Group groupRow = new Group {
        LeagueId = league.LeagueId, 
        User = currentUser, 
        TeamName = "Commish", 
        LeagueSeason = league.CurrentSeason, 
        OwnerRole = "Commissioner"};
      _db.Groups.Add(groupRow);
      _db.SaveChanges();
      Standing standing = new Standing {
        LeagueId = league.LeagueId,
        GroupId = groupRow.GroupId,
        TeamName = groupRow.TeamName,
        Wins = 0,
        Ties = 0,
        Losses = 0,
        PtsFor = 0,
        PtsAgst = 0,
        LeagueName = league.LeagueName
      };
      _db.Standings.Add(standing);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public async Task<ActionResult> Details(int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var currentGroupId = _db.Groups.FirstOrDefault(x => x.LeagueId == id && x.User.Id == currentUser.Id);
      if(currentGroupId != null)
      {
        if(currentGroupId.OwnerRole == "Commissioner")
        {
          ViewBag.Owner = true;
        }
      }
      var league = _db.Leagues.FirstOrDefault(x => x.LeagueId == id);
      List<Group> model = _db.Groups.Where(x => x.LeagueId == id && x.LeagueSeason == league.CurrentSeason).ToList();
      ViewBag.League = league;
      return View(model);
    }    

    // [Authorize(Roles = "Administrator")]
    public ActionResult Edit(int id)
    {
      var thisLeague = _db.Leagues.FirstOrDefault(x => x.LeagueId == id);
      return View(thisLeague);
    }
    
    // [Authorize(Roles = "Administrator")]
    [HttpPost]
    public ActionResult Edit(League league)
    {
      _db.Entry(league).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = league.LeagueId});
    }
    [HttpPost]
    public ActionResult Index(string Name)
    {
      List<League> model = _db.Leagues.Where(x => x.LeagueName.Contains(Name)).ToList();
      return View("Index", model);
    }
    public ActionResult Join(int id)
    {
      ViewBag.League = _db.Leagues.FirstOrDefault(x => x.LeagueId == id);
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Join(Group group)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var league = _db.Leagues.FirstOrDefault(x => x.LeagueId == group.LeagueId);
      Group groupRow = new Group {
        LeagueId = group.LeagueId, 
        User = currentUser, 
        TeamName = group.TeamName, 
        LeagueSeason = league.CurrentSeason, 
        OwnerRole = "Owner"};
      _db.Groups.Add(groupRow);
      _db.SaveChanges();
      Standing standing = new Standing {
        LeagueId = league.LeagueId,
        GroupId = groupRow.GroupId,
        TeamName = groupRow.TeamName,
        Wins = 0,
        Ties = 0,
        Losses = 0,
        PtsFor = 0,
        PtsAgst = 0,
        LeagueName = league.LeagueName
      };
      _db.Standings.Add(standing);
      _db.SaveChanges();
      return RedirectToAction("Details", new {id = group.LeagueId});
    }
    public ActionResult RemoveOwner(int id)
    {
      var model = _db.Groups.FirstOrDefault(x => x.GroupId == id);
      return View(model); 
    }
    public ActionResult ConfirmRemove(int id)
    {
      Group groupToBeInactive = _db.Groups.FirstOrDefault(x => x.GroupId == id);
      groupToBeInactive.Active = 0;
      _db.Entry(groupToBeInactive).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new {groupToBeInactive.LeagueId});
    }

    public ActionResult Commish(int id)
    {
      League l = _db.Leagues.FirstOrDefault(x => x.LeagueId == id);
      
      return View(l);
    }
  }
}

HFSclient/Controllers/StandingsController.cs
using Microsoft.AspNetCore.Mvc;
using HFSclient.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;  
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
namespace HFSclient.Controllers 
{
  public class StandingsController : Controller
  {
    private readonly HFSclientContext _db;
    public StandingsController(HFSclientContext db)
    {
      _db = db;  
    }
    public IActionResult Index(int id)
    {
      List<Standing> model= _db.Standings.Where(x => x.LeagueId == id).OrderByDescending(x => x.Wins).ToList();
      return View(model);
    } 
  }
}

HFSclient/Views/Standings/Index.cshtml
@{
  Layout = "_Layout";
}
@using HFSclient.Models;


@if (@Model.Count == 0)
{
  <h3>No Standings are available!</h3>
}
else
{
   <table cellpadding="3" cellspacing="1" class="Standings" width="575"><tr class="masthead_alt"><td bgcolor="#FFFFFF" colspan="5">
    
    </td></tr>
    <tr class="stathead">
    <td width="40%">TEAM</td>
    <td align="right" width="15%">Wins</td>
    <td align="right" width="15%">Losses</td>
    <td align="right" width="15%">Ties</td>
    <td align="right" width="15%">PCT</td>
    <td align="right" width="15%">PointsFor</td>
    <td align="right" width="15%">PointsAgainst</td>
    @foreach (Standing x in @Model)
    {
      <tr class="evenrow">
        <td>@x.TeamName</td>
        <td align="right">@x.Wins</td>
        <td align="right">@x.Losses</td>
        <td align="right">@x.Ties</td>
        <td align="right">@((double)(@x.Wins / (double)( @x.Wins + @x.Losses + @x.Ties)))</td>
        <td align="right">@x.PtsFor</td>
        <td align="right">@x.PtsAgst</td>
    </tr>

    }
  </table>
  @Html.ActionLink(" Back", "Details", "Leagues", new { id = @Model[0].LeagueId}, new { @class = "btn btn-info"})
}
























@* <div id="Standings">
  <div class = "Card">
    
   <table cellpadding="3" cellspacing="1" class="Standings" width="575"><tr class="masthead_alt"><td bgcolor="#FFFFFF" colspan="5">
    
    <span style="color:#FFFFFF">Name of League</span>
    </td></tr>
    <tr class="stathead">
    <td width="40%">TEAM</td>
    <td align="right" width="15%">Wins</td>
    <td align="right" width="15%">Losses</td>
    <td align="right" width="15%">PCT</td>
    <td align="right" width="15%">CONF</td>
    <td align="right" width="15%">GB</td>
    <td align="right" width="15%">PointsFor</td>
    <td align="right" width="15%">PointsAgainst</td>
    @for (int i = 0; i < @model.count; i++)
    {
        if(i%2 == 0){
          <tr class="oddrow"><td>team 1</td><td align="right">@model.Wins</td><td align="right">@model.Losses</td><td align="right">@model.Wins/@model.Losses</td><td align="right" class="active">0</td><td align="right">0</td><td align="right">@model.PtsFor</td><td align="right">@model.PtsAgst</td></tr>
        }
        else{
          <tr class="evenrow"><td>team 2</td><td align="right">@model.Wins</td><td align="right">@model.Losses</td><td align="right">@model.Wins/@model.Losses</td><td align="right" class="active">0</td><td align="right">0</td><td align="right">@model.PtsFor</td><td align="right">@model.PtsAgst</td></tr>
        }
    }
     







  
    
  
  
  </table>

  </div>
</div> *@


@*  <table cellpadding="3" cellspacing="1" class="Standings" width="575"><tr class="masthead_alt"><td bgcolor="#FFFFFF" colspan="5">
    
    <span style="color:#FFFFFF">Name of League</span>
    </td></tr><tr class="stathead">
    <td width="40%">TEAM</td>
    <td align="right" width="15%">Wins</td>
    <td align="right" width="15%">Losses</td>
    <td align="right" width="15%">PCT</td>
    <td align="right" width="15%">CONF</td>
    <td align="right" width="15%">GB</td>
    <td align="right" width="15%">PointsFor</td>
    <td align="right" width="15%">PointsAgainst</td>
    </tr>
    <tr class="oddrow"><td>team 1</td><td align="right">0</td><td align="right">0</td><td align="right">0</td><td align="right" class="active">0</td><td align="right">0</td><td align="right">0</td><td align="right">0</td></tr>
    <tr class="evenrow"><td>team 2</td><td align="right">0</td><td align="right">0</td><td align="right">0</td><td align="right" class="active">0</td><td align="right">0</td><td align="right">0</td><td align="right">0</td></tr>
    <tr class="oddrow"><td>team 3</td><<td align="right">0</td><td align="right">0</td><td align="right">0</td><td align="right" class="active">0</td><td align="right">0</td><td align="right">0</td><td align="right">0</td></tr>
    <tr class="evenrow"><td>team 4</td><td align="right">0</td><td align="right">0</td><td align="right">0</td><td align="right" class="active">0</td><td align="right">0</td><td align="right">0</td><td align="right">0</td></tr>
    <tr class="oddrow"><td>team 5</td><td align="right">0</td><td align="right">0</td><td align="right">0</td><td align="right" class="active">0</td><td align="right">0</td><td align="right">0</td><td align="right">0</td></tr>
    <tr class="evenrow"><td>team 6</td><td align="right">0</td><td align="right">0</td><td align="right">0</td><td align="right" class="active">0</td><td align="right


  ">0</td><td align="right">0</td><td align="right">0</td></tr>
  
  </table> *@